(lang dune 3.21)

(name proj_jsonschema-validation)

(generate_opam_files false)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name proj_jsonschema-validation)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
 (ocaml (= 5.5.0)) relocatable

jsonschema-validation ; DEP
)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
