(lang dune 3.21)

(name foo)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name foo)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends (ocaml (= 5.5.0)) relocatable bar)
 (tags
  ("add topics" "to describe" your project)))

(pin
  (url file://../bar)
  (package (name bar)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
